blank_issues_enabled: false

contact_links:
  - name: ä½¿ç”¨æ–‡æ¡£
    url: http://furion.baiqian.ltd/
    about: è®© .NET å¼€å‘æ›´ç®€å•ï¼Œæ›´é€šç”¨ï¼Œæ›´æµè¡Œã€‚
  - name: VIP æœåŠ¡ ğŸ¤œğŸ¤›
    url: http://furion.baiqian.ltd/docs/subscribe
    about: å¼€é€š VIP æœåŠ¡ä»…éœ€ 799 å…ƒï¼Œå°Šäº« 365 å¤©é¡¹ç›®æ— å¿§
  - name: æ…·æ…¨èµåŠ©
    url: http://furion.baiqian.ltd/docs/donate
    about: å…è®¸å•†ç”¨ï¼Œæ…·æ…¨èµåŠ©
  - name: å¾®ä¿¡å…¬ä¼—å·
    url: https://gitee.com/dotnetchina/Furion/raw/v4/handbook/static/img/weixin_qrcode.jpg
    about: å…³æ³¨ Furion å…¬ä¼—å·è®¢é˜…æœ€æ–°èµ„è®¯
